[template]
 src   = "cluster.xml.tmpl"
 dest  = "/app/conf/cluster.xml"
 keys = [
  "/cluster/group/name",
  "/cluster/group/password",
  "/cluster/public/address",
  "/cluster/aws",
  "/cluster/aws/region",
  "/cluster/aws/iam/role",
  "/cluster/aws/tag/key",
  "/cluster/aws/tag/value",
  "/cluster/port"
 ]