[template]
 src   = "cluster.xml.tmpl"
 dest  = "/app/conf/cluster.xml"
 keys = [
  "/cluster/group/name",
  "/cluster/group/password",
  "/cluster/aws",
  "/cluster/aws/group",
  "/cluster/aws/iam",
  "/cluster/port",
  "/aws/default/region"
 ]